# Generated by Django 2.2.4 on 2019-09-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
