# Generated by Django 2.2.4 on 2019-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0004_auto_20190909_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('uidBlog', models.IntegerField(primary_key=True, serialize=False)),
                ('nameBlog', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('phone', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='junk',
            fields=[
                ('movid', models.IntegerField(primary_key=True, serialize=False)),
                ('movname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uidPerson', models.IntegerField()),
                ('namePerson', models.CharField(max_length=20)),
            ],
        ),
    ]
