# Generated by Django 2.2.4 on 2019-09-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_blogs_details_junk_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='junk',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
