# Generated by Django 2.2.4 on 2019-09-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('uidBlog', models.IntegerField(primary_key=True, serialize=False)),
                ('nameBlog', models.CharField(max_length=20)),
            ],
        ),
    ]
