# Generated by Django 2.2.4 on 2019-09-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0009_auto_20190909_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('usn', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
