# Generated by Django 2.2.4 on 2019-10-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=50)),
                ('act_gender', models.CharField(max_length=1)),
                ('act_bio', models.CharField(max_length=200)),
                ('act_picURL', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('dir_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dir_name', models.CharField(max_length=50)),
                ('dir_phone', models.IntegerField()),
                ('dir_bio', models.CharField(max_length=500)),
                ('dir_picURL', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='movie_directedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.director')),
            ],
        ),
        migrations.CreateModel(
            name='movieactor_awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.CharField(max_length=50)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.actor')),
            ],
            options={
                'unique_together': {('act_id', 'awards')},
            },
        ),
        migrations.CreateModel(
            name='moviecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.actor')),
            ],
        ),
        migrations.CreateModel(
            name='moviedirector_awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.CharField(max_length=50)),
                ('dir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.director')),
            ],
            options={
                'unique_together': {('dir_id', 'awards')},
            },
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('mov_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mov_title', models.CharField(max_length=50)),
                ('mov_year', models.IntegerField()),
                ('mov_lang', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('movie_picurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=2, max_digits=2)),
                ('reviews', models.CharField(max_length=100)),
                ('mov_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.movies')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('user_id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.userinfo'),
        ),
        migrations.AddField(
            model_name='moviecast',
            name='mov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
        migrations.AddField(
            model_name='movie_directedby',
            name='mov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'mov_id')},
        ),
        migrations.AlterUniqueTogether(
            name='moviecast',
            unique_together={('act_id', 'mov_id')},
        ),
        migrations.AlterUniqueTogether(
            name='movie_directedby',
            unique_together={('mov_id', 'dir_id')},
        ),
    ]
