# Generated by Django 2.2.4 on 2019-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20191012_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_directedby',
            name='height',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='movieactor_awards',
            name='height',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='moviedirector_awards',
            name='height',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
