# Generated by Django 2.2.4 on 2019-10-13 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20191012_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_directedby',
            name='dir_id',
            field=models.ForeignKey(db_column='dir_id', on_delete=django.db.models.deletion.CASCADE, to='movie.director'),
        ),
        migrations.AlterField(
            model_name='movie_directedby',
            name='mov_id',
            field=models.ForeignKey(db_column='mov_id', on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
        migrations.AlterField(
            model_name='movieactor_awards',
            name='act_id',
            field=models.ForeignKey(db_column='act_id', on_delete=django.db.models.deletion.CASCADE, to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='act_id',
            field=models.ForeignKey(db_column='act_id', on_delete=django.db.models.deletion.CASCADE, to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='mov_id',
            field=models.ForeignKey(db_column='mov_id', on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
        migrations.AlterField(
            model_name='moviedirector_awards',
            name='dir_id',
            field=models.ForeignKey(db_column='dir_id', on_delete=django.db.models.deletion.CASCADE, to='movie.director'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='mov_id',
            field=models.ForeignKey(db_column='mov_id', on_delete=django.db.models.deletion.PROTECT, to='movie.movies'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='movie.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
