# Generated by Django 2.2.4 on 2019-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20191013_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='act_bio',
            field=models.CharField(max_length=10000),
        ),
    ]
