# Generated by Django 2.2.4 on 2019-10-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20191013_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedirector_awards',
            name='id',
        ),
        migrations.AlterField(
            model_name='moviedirector_awards',
            name='dir_id',
            field=models.ForeignKey(db_column='dir_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.director'),
        ),
    ]
