# Generated by Django 2.2.4 on 2019-10-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20191016_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieactor_awards',
            name='id',
        ),
        migrations.AlterField(
            model_name='movieactor_awards',
            name='act_id',
            field=models.ForeignKey(db_column='act_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.actor'),
        ),
    ]
