# Generated by Django 2.2.4 on 2019-10-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_auto_20191016_0959'),
        ('movie', '0016_auto_20191018_1404'),
    ]

    operations = [
    ]
