# Generated by Django 2.2.4 on 2019-10-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_merge_20191023_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='mov_id',
            field=models.ForeignKey(db_column='mov_id', on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
    ]
